# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  
  lane :beta do
    gym(
      scheme: "HelloJenkinsAndFastlane",
      export_method: "Development",
      clean: true,
      skip_profile_detection: true,
      output_name: "HelloJenkinsAndFastlane.ipa",
      output_directory: "~/Desktop",
      export_options:{
        signingStyle: "manual",
          provisioningProfiles:{
            "com.vbadisova.HelloJenkinsAndFastlane" => "com.vbadisova.HelloJenkinsAndFastlane Development",
          }
      }
    )
  end

  lane :refreshJenkinsKeychain do
    delete_keychain(name: "jenkins") if File.exists? File.expand_path("~/Library/Keychains/jenkins-db")
    create_keychain(
      name: "jenkins",
      password: "jenkins",
      timeout: false,
      lock_when_sleeps: false,
      unlock: true
    )
  end

  lane :matchPopulateJenkinsKeychain do
    #register_devices(devices_file: "./fastlane/devices.txt")
#
#    match(
#      type: "development",
#      git_url: "https://github.com/Tolstyachok56/HelloJenkinsAndFastlane.git",
#      git_branch:"master",
#      username:"vbadisova@gmail.com",
#      app_identifier: [
#        "com.vbadisova.HelloJenkinsAndFastlane"
#      ]
#    )

  get_certificates(
    generate_apple_certs: true,
    type: "development",
    username: "vbadisova@gmail.com",
    keychain_path: "~/Library/Keychains/jenkins-db",
    keychain_password: "jenkins"
  )
  end
  
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
