# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  
  lane :beta do
    gym(
      scheme: "HelloJenkinsAndFastlane",
      export_method: "development",
      clean: true,
      output_name: "HelloJenkinsAndFastlane.ipa",
      output_directory: "~/Desktop"
    )
  end

  lane :refreshJenkinsKeychain do
    delete_keychain(name: "jenkins") if File.exists? File.expand_path("~/Library/Keychains/jenkins-db")
    create_keychain(
      name: "jenkins",
      password: "jenkins",
      timeout: false,
      lock_when_sleeps: false,
      unlock: true
    )
  end

  lane :matchPopulateJenkinsKeychain do
  cert(
    generate_apple_certs: true,
    development: true,
    username: "vbadisova@gmail.com",
    keychain_path: "~/Library/Keychains/jenkins-db",
    keychain_password: "jenkins"
  )
  sign(
    development: true
  )
  end
  
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
